# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - final-custom-container-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: sitecontainerssampleacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_CC07A6E4F6BA416BA582738F89DB4FA3 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_624167ED1C594EBB977C28B8B725D886 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sitecontainerssampleacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_CC07A6E4F6BA416BA582738F89DB4FA3 }}/sitecontainerssampleacr/test/router-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BBD02BFA69D3483C97EEC97029390C83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A0278AC074AD439D8970D2E9B8537B20 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81F77D48FD5A4F91AAC700C683B67705 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'final-custom-container-app'
          slot-name: 'Production'
          images: 'sitecontainerssampleacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_CC07A6E4F6BA416BA582738F89DB4FA3 }}/sitecontainerssampleacr/test/router-app:${{ github.sha }}'
          